export const ADD_COMMENT = 'ADD_COMMENT';
export const DONATIONS_LOADING = 'DONATIONS_LOADING';
export const DONATIONS_FAILED = 'DONATIONS_FAILED';
export const ADD_DONATIONS = 'ADD_DONATIONS';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
